### ISSUE TITLE
`propertychange` on an input[type=radio] with this.checked fires standard onChange

### ISSUE THREAD

**Issue by DimitarChristoff** [mootools/mootools-core#2170]
http://jsfiddle.net/5CvBb/5/

``` javascript
document.getElements("input").addEvents({
    "change": function() {
        alert("change");
    }
});


document.id("dom").removeClass("validation-failed");
```

run this with a simple dom of:
`<input type="radio" name="foo" value="yes" class="validate-one-required" /> yes
<input id="dom" type="radio" name="foo" value="no" checked="checked" /> no    
`
possibly to do with the new Event Delegation when w/o eventListenerSupport, this does not break in 1.3.2 or earlier.

**Comment by tom-field** [comment]
我会
