### ISSUE TITLE
Uncaught TypeError: Cannot set property '$prototyping' of undefined

### ISSUE THREAD

**Issue by SethArchambault** [mootools/mootools-core#2338]
Hit this error when I Extended a class that was declared after the current class.

**Comment by Ezequiel-Vega** [comment]
Hi i have same mistake with mootools 1.4.5, this is el error that i get
![errorGIthub](https://user-images.githubusercontent.com/39246608/128747925-f1445f1e-4b37-4a6e-af9e-850661125c25.png)

**Comment by DimitarChristoff** [comment]
So, you're extending a Class that isn't there. check CentralTopic.js - in today's world, ensure you run mootools 1.6 - 1.4.5 is from 2012...
