### ISSUE TITLE
relatedTarget not set for mouse leave events

### ISSUE THREAD

**Issue by zenlunatics** [mootools/mootools-core#2348]
I noticed that in core 1.4.5 relatedTarget was not being set in Firefox for mouseleave events. modifying the line 

    if (type == 'mouseover' || type == 'mouseout'){

in DOMEvent by adding `|| type == 'mouseleave'` seems to fix the problem.

**Comment by arian** [comment]
That line: https://github.com/mootools/mootools-core/blob/3e9875e6d/Source/Types/DOMEvent.js#L67

**Comment by arian** [comment]
That's the fix: http://jsfiddle.net/b67n43em/1/

**Comment by arian** [comment]
```js
function fix(e) {
    var event = e.event;
    if (event.type == 'mouseenter') {
        e.relatedTarget = event.fromElement;
    }
    if (event.type == 'mouseleave') {
        e.relatedTarget = event.toElement;
    }
}
```
