### ISSUE TITLE
Request.JSON default Content-type

### ISSUE THREAD

**Issue by SmokeyXL** [mootools/mootools-core#2361]
For your next version of mootools please consider:
- Setting the default Content-type to 'application/json' in the headers of a Request.JSON

The following two classes in JSON-RPC for PHP expects this to be set. (http://jsonrpcphp.org/)
- jsonRPCServer
- jsonRPCClient

All that is required is the following changes in Request.JSON

initialize: function(options){
  this.parent(options);
    Object.append(this.headers, {
      <b>'Content-type' : 'application/json',</b>
      'Accept': 'application/json',
      'X-Request': 'JSON'
  });
}

Thank you very much!

**Comment by ricardograca** [comment]
@sebmarkbage Can you elaborate on those "better, completely different, API suggestions that is more likely to replace Request.JSON"?

I can only think of the standard Request, but that seems to defeat the point of Request.JSON.
