### ISSUE TITLE
Mootools overrides Function.prototype.bind with a non-standard version

### ISSUE THREAD

**Issue by aviynw** [mootools/mootools-core#2473]
The way chrome, firefox, and IE10 all implement Function.prototype.bind is to accept first a "this" arg, followed by an arbitrary number of arguments.  However mootools expects the arguments to be put into an array.  Running the below the example with and without mootools on the page will illustrate the point.
    var p = function(a, b){
    alert(a);
    alert(b);
    }
    var t = p.bind(null, 'a','b');
    t();

The second problem is that in chrome firefox and ie10 you are able to call bind multiple times such that for a function t, t.bind(null, 'a').bind(null, 'b'); t(); would execute "t" with both a and b as prepended arguments.  With mootools this also doesn't work.

But for me the real problem isn't the faulty implementation but the fact that mootools overrides the native implementation.  This problem came up in a library I was writing that is completely independent of mootools.  Someone tried to use the library I was writing with mootools on the same page, and boom!  If you want add methods to native prototypes, you should use names that aren't in the ecmascript standard, to avoid conflicting with other scripts.  From your perspective I don't know how you can fix this without breaking backwards compatibility, but if you don't fix this, your library is incompatible with any script that uses function.bind without mootools.

**Comment by dvdplm** [comment]
AFAICT this is still an issue.
JSBin with mootools and @aviynw's snippet: http://jsbin.com/qamewuheni/2/edit
JSBin without mootools and @aviynw's snippet: http://jsbin.com/waxecizeya/1/edit

I'm in the same situation where I can't easily fix the hosting page and mootools' presence in the page ruins the party for my code.

**Comment by arian** [comment]
@dvdplm, the outputs are the same for me... which is correct because you use the nocompat version.

**Comment by dvdplm** [comment]
@arian yes, you are right. I was (wrongly) under the impression that post v1.2 you'd have to opt-in to the broken stuff rather than the other way around.
