### ISSUE TITLE
focusin/focusout events does not work in firefox

### ISSUE THREAD

**Issue by moldcraft** [mootools/mootools-core#2524]
Firefox version 23.0, Ubuntu 12.04

In IE7, IE8 and Chrome 28 works fine

Especially I need that functionality for selects

At the moment I did a temporary "hack":

``` javascript
var $select = $('select-id');

var events = {
    focusin: function(){
        if ($select.getAttribute('data-focus') == 'in') {
            return;
        } else {
            $select.setAttribute('data-focus', 'in');
        }

        // ...
    },
    focusout: function(){
        if ($select.getAttribute('data-focus') == 'out') {
            return;
        } else {
            $select.setAttribute('data-focus', 'out');
        }

        // ...
    }
};

events.focus = events.focusin;
events.blur  = events.focusout;

$select.addEvents(events);
```

I can't use focus and blur because I change select's options dynamically on focusin and in IE this does not work properly with focus: It closes back select when clicked to open, and need to click again (without loosing focus) to open.
##

**Comment by SergioCrisostomo** [comment]
This is fixed in Firefox 52. Closing.
