### ISSUE TITLE
scroll event does not pass event object

### ISSUE THREAD

**Issue by DimitarChristoff** [mootools/mootools-core#2607]
``` javascript
document.addEventListener('scroll', function(event) {
    console.log(event); // token event object, can't be cancelled etc but...
});

document.addEvent('scroll', function(event) {
  console.log(event); // undefined
});
```

reported here: http://stackoverflow.com/questions/24016119/no-event-object-on-scroll-event-in-mootools

it shouldn't fail because event type is set to 1 hence it should run this code:

https://github.com/mootools/mootools-core/blob/master/Source/Element/Element.Event.js#L47-L55 - so `addListener` may be at fault.

not sure why, though. it's plain enough and should use `addEventListener`
https://github.com/mootools/mootools-core/blob/master/Source/Element/Element.js#L935-L942

**Comment by giann** [comment]
So how can we distinct scroll from scroll down ?
