### ISSUE TITLE
DELETE ajax request fails on Safari (OS X & iOS)

### ISSUE THREAD

**Issue by PanzerKunst** [mootools/mootools-core#2625]
Hi,

When doing the following DELETE request on the latest Safari browsers (OS X and iOS), the `onFailure` callback is executed:

    new Request({
        urlEncoded: false,
        emulation: false, // Otherwise PUT and DELETE requests are sent as POST
        url: url,
        onSuccess: function (responseText, responseXML) {
            alert("AJAX success :)");
        },
        onFailure: function (xhr) {
            alert("AJAX fail :(");
        }.bind(this)
    }).delete();

This happens because Mootools sets a Content-Type header to the XHR, and Safari refuses to send DELETE XHRs with a Content-Type.

To reproduce: 
1. Set up a server which listens to DELETE requests on `url`
2. Set up a web page with the above Javascript code
3. Execute the page in a browser other than Safari. Check that the server receives the request, and that the "AJAX success :)" popup is displayed
4. Execute the page in Safari. Witness the failure

**Comment by ibolmo** [comment]
We've tried to replicate the issue, but we were unsuccessful. Please provide more detail.
