### ISSUE TITLE
typeOf( window.parent ) throws error if the parent window is owned by different domain

### ISSUE THREAD

**Issue by ickata** [mootools/mootools-core#2660]
Very rare case, but very interesting. If I pass a `window` object, owned by another domain, to `typeOf`, this throws error due to disallowed access to the `$family` property. The same domain origin policy allow us to refer to window objects of other domains, but not to access their properties. Therefore, I think `typeOf` should be able to return "window" in that case.

How I caught this bug: I have array with 2 items - `window` and `parent` in a property of an `options` object in a `Class` prototype. Then, I try to set options with the `setOptions` method, which calls `typeOf` in it. I have an environment where my current window and its parent are both owned by me, but there's a case where the parent is not mine.

Anyway - if you think this bug is worth fixing, I can fix & make a pull request.

**Comment by ibolmo** [comment]
Two issues. 

typeOf checking $family on a secure object. We don't know of a way to test an object if it's secure or from another domain. Let us know, if you find a way to do this. Just trying `'setTimeout' in window.parent` in jsFiddle for example, throws an error. 

setOptions in Class. We never intended to pass elements, and other _massive_ objects to setOptions. We encourage you to instead pass them to the constructor, or as keys to lookup. E.g. IDs. 

As it is, we'll have to close this, but open to suggestions on the secure objects.

**Comment by ickata** [comment]
I agree with your note about `setOptions`, but believe me - this is something that I cannot avoid.

You don't have any way to access any object from another domain except `window` and some of its properties. That's why my proposal for fix is the following - add a new line right after line 33: https://github.com/mootools/mootools-core/blob/master/Source/Core/Core.js#L33

`if (item.location && item.parent && item.self && item.top && (item.opener === null || item.opener)) return 'window';`

**Comment by ibolmo** [comment]
Out of the properties that you are checking, `location` `top` and `opener` seem _least generic_, but I could *still* imagine someone passing `{location: 'Hollywood'}` and instead of `object` being returned, they'll get `window`. 

Is there other *unique* properties we could check for?

**Comment by ibolmo** [comment]
Untested, but maybe... `if (item.top && !Object.hasOwnProperty(item, 'top')) return 'window';`

**Comment by ickata** [comment]
I think it is more safe to check for all properties that the cross-domain restriction allows us. These are "location", "parent", "self", "top" and "opener". The more properties we check for, the better chance we have not to detect some regular object as `window`.
