### ISSUE TITLE
String.prototype.capitalize() isn't corretly capitalizing words with accents

### ISSUE THREAD

**Issue by andreynering** [mootools/mootools-core#2680]
Some languages like spanish and portuguese have words with accents. MooTools isn't correctly capitalizing these words:

```js
'música'.pluralize() //MúSica
```

An example in JSFiddle: http://jsfiddle.net/3xLjf6t9/

**Comment by SergioCrisostomo** [comment]
We decided yesterday we will leave this method as it is since we cannot include all cases in a simple solution that is not expensive for performance. Also this method is used mostly for internal purposes.

@andreynering happy my idea was usable! Cheers

**Comment by andreynering** [comment]
Thank you for the feedback.

--
Andrey Nering
Em 15/01/2015 11:29, "Sergio Crisostomo" <notifications@github.com>
escreveu:
