### ISSUE TITLE
Remove All Prototype Definitions from Builtins

### ISSUE THREAD

**Issue by jacobp100** [mootools/mootools-core#2683]
This has already affected ES6, with it's now non-intuitive String|Array.includes. This will only continue if you keep doing this.

Or minimally, force-overwrite the existing definitions, so new standards won't conflict.

**Comment by SergioCrisostomo** [comment]
@jacobp100 thanks for your input. Point registered.
I close this issue since its generic about extending prototypes.

Cheers
