### ISSUE TITLE
Element.dispose() - Do not remove ID's

### ISSUE THREAD

**Issue by kije** [mootools/mootools-core#2690]
Element.dispose() removes a element from DOM and returns it. However, the id attribute of the returned Element(s) is removed. 
There should be at least a possibility (parameter) to make dispose() not remove the id attribute.

**Comment by arian** [comment]
`dispose` should not remove the ID attribute.

http://jsfiddle.net/4cm2h8rb/ shows that this indeed does not happen.

In which situation is the attribute removed for you?

**Comment by DimitarChristoff** [comment]
@arian probably `el.clone().dispose()` - though that's kind of pointless given that clone does not add a `parentNode` anyway. 

suggest close.

**Comment by SergioCrisostomo** [comment]
@kije please comment back if you can make a _jsFiddle_ reproducing the problem you pointed out.
