### ISSUE TITLE
Make it easy to run tests in arbitrary browsers

### ISSUE THREAD

**Issue by jdm** [mootools/mootools-core#2706]
For web browsers that don't have pre-existing definitions, it would be valuable to allow starting the test server and visiting a page in the browser of your choice, rather than relying on the test harness to do so.

**Comment by arian** [comment]
You can run karma with grunt. Using `grunt karma:dev`, you can open the test runner in any browser by opening the karma link.

**Comment by jdm** [comment]
Thanks, that seems to do the trick.
