### ISSUE TITLE
Instance properties (object type) are broken in node

### ISSUE THREAD

**Issue by 131** [mootools/mootools-core#2709]
Class seems to be broken in nodejs (on a very core component), can someone help me there ?
```
//npm install mootools
//require('mootools');
var Foo =  Class({
  config : {'paris':23,'ny':22},
  initialize:function(){
    console.log(this.config);
  }
});
var foo = new Foo();
```
 Excepted output :  Object { paris=23, ny=22}<br/>
In jsFiddle :all is fine http://jsfiddle.net/taL8bfjb/1/<br/>
 Got : {}<br/>

http://jsfiddle.net/taL8bfjb/1/

**Comment by GCheung55** [comment]
It's not actually broken. Try printing out:

```javascript
console.log(this.config.paris);
```

This is happening because Class copies each property into a brand new prototype and inherits from it. That's why `this.config.hasOwnProperty('paris')` would return false, and yet looking up the property will return the value.

**Comment by 131** [comment]
console.log(Object.keys(this.config).length); => 0

Even though, as you said, this.config.paris is set 
This is still a major issue.

**Comment by DimitarChristoff** [comment]
it's a bad practice to store non primitives in the prototype as they are not immutable and can introduce nasty side effects by reference if instances modify them.

**Comment by DimitarChristoff** [comment]
... the notable exception being `options` which is handled correctly via the `setOptions` mixin

**Comment by SergioCrisostomo** [comment]
I made a example in jsFiddle that makes Browser console behave more like NodeJS's console, not giving it the chance to change the object along the way.

http://jsfiddle.net/drqkzw6d/

This was a interesting issue and you guys left really nice feedback.
I close this now. Please comment more if you feel I did wrong.
