### ISSUE TITLE
Chrome 44 (Canary) introduces breaking changes within MooTools

### ISSUE THREAD

**Issue by restlessdesign** [mootools/mootools-core#2711]
This can be observed on http://mootools.net/more/builder (1.5.1) and https://vimeo.com (1.4.5)

> Uncaught TypeError: Number.prototype.valueOf is not generic
> Uncaught TypeError: window.addEvent is not a function
> Uncaught ReferenceError: Class is not defined

**Comment by SergioCrisostomo** [comment]
Related: https://code.google.com/p/chromium/issues/detail?id=475832

**Comment by dimarwix** [comment]
Thanks, @SergioCrisostomo!

**Comment by chemix** [comment]
from code.goole
"
JSBin http://jsbin.com/dumupilogu/1/edit

Problem is related to a change in the V8 - "ES6: Number and Boolean prototype should be ordinary objects."
But this is normal behavior for ES6, need fix the problem in Mootools
"

**Comment by dimarwix** [comment]
@chemix - this comment wasn't added by a Google representative. This is a regression bug in Chrome and it was assigned. Note the status change slightly above this comment:

> Status: Assigned 
> Labels: -Type-Bug -Needs-Feedback Type-Bug-Regression

**Comment by chemix** [comment]
ok, I hove someone will fix it :)

**Comment by chemix** [comment]
today's night build works :)

**Comment by SergioCrisostomo** [comment]
Nice! 

@restlessdesign could you confirm this and close this issue if the problem is gone?

Thank you

**Comment by restlessdesign** [comment]
Confirmed!
