### ISSUE TITLE
get unspecified error (this.getBoundingClientRect) while loading mootools core 1.5.1 in I.E. 11

### ISSUE THREAD

**Issue by j3zusla** [mootools/mootools-core#2712]
Hello,

I have fixed the 'email' issue in core 1.5.1... Now, I am not able to pass the following error in I.E. 11 while loading the library:

unspecified error. @line 402:	var p=this.getBoundingClientRect();

The code works fine in Firefox and Chrome, Could you let me know what I should do to make the app work on I.E. 11?

Cordially,
INF1

**Comment by SergioCrisostomo** [comment]
@j3zusla could yourecreate the problem in jsFiddle? what environment are you using? how are you loading MooTools?

**Comment by j3zusla** [comment]
I am loading mootools via document.write:

document.write("<script charset=\"utf-8\" type=\"text/javascript\" src=\"/DHTML/lib/mootools-core-1.5.1-full-compat-yc.js\"></script>");

Sorry, I am not able to simulate the error with jsfiddle: "document.write is disallowed in JSFiddle envioriment and might break your fiddle." (the spelling error for environemnt is from the site itself ;) )

I could give you the live site if you are not able to reproduce the issue, but I prefer to keep it private to community for now. Thank you for your understanding and help,

Cordially,
JFSG

**Comment by DimitarChristoff** [comment]
you can use document.write in jsfiddle, don't tell zalun.

    var w = 'write', d = document;

    d[w]('hi');

just set the script block to in body.

On 22 April 2015 at 21:40, j3zusla <notifications@github.com> wrote:

> I am loading mootools via document.write:
>
> document.write("");
>
> Sorry, I am not able to simulate the error with jsfiddle: "document.write
> is disallowed in JSFiddle envioriment and might break your fiddle." (the
> spelling error for environemnt is from the site itself ;) )
>
> I could give you the live site if you are not able to reproduce the issue,
> but I prefer to keep it private to community for now. Thank you for your
> understanding and help,
>
> Cordially,
> JFSG
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mootools/mootools-core/issues/2712#issuecomment-95328259>
> .
>



-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by j3zusla** [comment]
cool I'll try that...

**Comment by j3zusla** [comment]
Soz, I have no luck duplicating the issue on fiddle. I have tried to include the lib via Fiddle external function and it is all fine on I.E. It must be a code conflict between libs. I have no choice but to give you the live url. Can I send it in private somehow?

**Comment by DimitarChristoff** [comment]
are you animating/revealing on load?

you've tried the obvious here (cache)?
http://stackoverflow.com/questions/19275088/in-google-maps-getboundingclientrect-gives-unspecified-error-in-ie

this can normally happen if you measure dimensions (getSize() etc) of an
element that's not in the DOM and has no layout, or you've morphed
something like height or width to a negative value.

On 22 April 2015 at 22:30, j3zusla <notifications@github.com> wrote:

> Soz, I have no luck duplicating the issue on fiddle. I have tried to
> include the lib via Fiddle external function and it is all fine on I.E. It
> must be a code conflict between libs. I have no choice but to give you the
> live url. Can I send it in private somehow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mootools/mootools-core/issues/2712#issuecomment-95343739>
> .
>



-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by DimitarChristoff** [comment]
yeah here's how to reproduce it easily in IE:

http://jsfiddle.net/q5mxu4y2/

all it takes is: new Element('div').getPosition();

pretty sure we discussed this a while ago and a try / catch block around it
that returns { top: this.offsetTop, left: this.offsetLeft } instead.



On 22 April 2015 at 22:38, Dimitar Christoff <christoff@gmail.com> wrote:

> are you animating/revealing on load?
>
> you've tried the obvious here (cache)?
> http://stackoverflow.com/questions/19275088/in-google-maps-getboundingclientrect-gives-unspecified-error-in-ie
>
> this can normally happen if you measure dimensions (getSize() etc) of an
> element that's not in the DOM and has no layout, or you've morphed
> something like height or width to a negative value.
>
> On 22 April 2015 at 22:30, j3zusla <notifications@github.com> wrote:
>
>> Soz, I have no luck duplicating the issue on fiddle. I have tried to
>> include the lib via Fiddle external function and it is all fine on I.E. It
>> must be a code conflict between libs. I have no choice but to give you the
>> live url. Can I send it in private somehow?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mootools/mootools-core/issues/2712#issuecomment-95343739>
>> .
>>
>
>
>
> --
> Dimitar Christoff
>
> "JavaScript is to JAVA what hamster is to ham"
> @D_mitar - https://github.com/DimitarChristoff
>



-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by j3zusla** [comment]
Yes DimitarChristoff, this is the issue I am getting!

**Comment by DimitarChristoff** [comment]
so stop trying to measure layout before injecting into the dom then or put
the try/catch around where you do it. we could fix getPosition to do it,
jquery have done--but it's kind of a nasty fix for an edgcase where it's
user error.

On Wednesday, April 22, 2015, j3zusla <notifications@github.com> wrote:

> Yes DimitarChristoff, this is the issue I am getting!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mootools/mootools-core/issues/2712#issuecomment-95349894>
> .
>


-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by j3zusla** [comment]
ok, I will back track and see where it gets called. I made sure to call what is needed on domready. It will give me the chance do a cleanup then! 

Hey DimitarChristoff plz, don't use jq word anymore, it gives me the creeps everytime  ;)

**Comment by DimitarChristoff** [comment]
one use case that you may have is like. `new
Element("foo").makeDraggable()` from more uses .getPosition() - if so, just
new Element('div').inject(someEl).makeDraggable()

in general, set some breakpoints and step through your code to find the
offending bit/plugin

**Comment by j3zusla** [comment]
Great, the I.E. 11 problem is now fixed . . .

The problem came from an old plugin (4-5 years old) called Fitimage.

The following line of code contains the issue:

this.image = new Element('img', {
                        'src': image,
                        'id': 'fitimage',
                        'class': this.options['class']
                }).addEvent('load', this.inject);


to make a quick fix, it got changed to:

this.image = new Element('img', {
                        'src': image,
                        'id': 'fitimage',
                        'class': this.options['class']
                }).inject(document.body);

Thank you everyone for all your help on that one and for that robust and performant moooooo library!

Much love to all, you deserve it,
J3zusla

**Comment by inf1** [comment]
Hello,

FYI: I can now release the website http://multivers3D.fr. 

It is using mootools at its core foundation and not the other libs;)

Cordially,
J3zusla

**Comment by SergioCrisostomo** [comment]
@inf1 / @j3zusla  happy you got it working!

I close this now. Cheers.
