### ISSUE TITLE
Object.keys return unwanted key

### ISSUE THREAD

**Issue by newbie78** [mootools/mootools-core#2714]
http://jsfiddle.net/syus4L73/ returned ["0", "1", "2", "3", "length"]
i think "length" unnecessary key or
how to receive an array without this key?

thanx

**Comment by DimitarChristoff** [comment]
you are calling it on a HTMLElement collection which is an array which is an object with array like properties like length. 

also this is handled by the browser natively in modern browsers. please ask questions on the mailing list instead, this is not an issue.
