### ISSUE TITLE
how can i make onchange select event firing?

### ISSUE THREAD

**Issue by newbie78** [mootools/mootools-core#2754]
see this fiddle plz
http://jsfiddle.net/96s4kq8m/1/

is that firing really plssible? and if no then why?
thanks very mutch

**Comment by swhiteman** [comment]
$('test').fireEvent('change');

This isn't a GitHub issue, so pls remove it. It should be on the mailing list mootools-users@googlegroups.com

**Comment by timwienk** [comment]
In your JSFiddle you the following error is thrown: `TypeError: $(...).fireEvents is not a function`.

The problem is indeed what Sandy just mentioned, you should use `fireEvent`, not "fireEvent***s***".

I will close this issue. If you need any other support, please ask on the mailing list:
https://groups.google.com/forum/#!forum/mootools-users

**Comment by newbie78** [comment]
yes. this is my mistake.
okay - thats work.

but why firing not work in this fiddle?
http://jsfiddle.net/96s4kq8m/2/

thanks again

**Comment by newbie78** [comment]
yes. this is my mistake.
okay - thats work.

but why firing not work in this fiddle?
http://jsfiddle.net/96s4kq8m/4/

thanks again

**Comment by newbie78** [comment]
please answ my q. in google mailing list forum no one answ me.

**Comment by DimitarChristoff** [comment]
so i answered this like 5 yrs ago. http://stackoverflow.com/questions/2689010/mootools-programmatically-fired-events-not-working-with-event-delegation - looks like mootools does not normalise and bubble native change events just yet.

**Comment by newbie78** [comment]
Dimitar, thanks for answer

http://jsfiddle.net/96s4kq8m/5/
How could i get the changed 'field' (see fiddle) by means of usual addEvent('change') ?

**Comment by newbie78** [comment]
maybe will we need to reopen the issues?

**Comment by newbie78** [comment]
http://jsfiddle.net/96s4kq8m/6/
fireEvent worked but undefined. why?
