### ISSUE TITLE
All mootools.net downloads are for 1.6.1dev

### ISSUE THREAD

**Issue by odysseuscm** [mootools/mootools-core#2762]
Hi, all core/more downloads on mootools.net, including the ones generated by the builders send out 1.6.1dev instead of 1.6.0.
Is that by design or a mistake?

**Comment by SergioCrisostomo** [comment]
@odysseuscm works for me... 

I get

```
this.MooTools = {
	version: '1.6.0',
	build: '529422872adfff401b901b8b6c7ca5114ee95e2b'
};
```

can you provide more info (browser, os)?

**Comment by timwienk** [comment]
That was a mistake, and is fixed now.

Something went wrong with tagging the release, so we ended up creating the tag later. Apparently we didn't re-fetch the repository on the web server for it to know about the tag, and it got stuck on master, rather than retrying.

**Comment by odysseuscm** [comment]
Curious: With Firefox 43.0.4 x64 on Windows 10 I always get 1.6.1dev, with Chrome I get 1.6.0

**Comment by timwienk** [comment]
Thanks for reporting! :+1:

**Comment by SergioCrisostomo** [comment]
Thanks for fixing @timwienk, the wrong release tagging was one me. Sorry for that.
