### ISSUE TITLE
Switch from irc to another communication platform?

### ISSUE THREAD

**Issue by chemix** [mootools/mootools-core#2763]
Like slack.com or gitter.im?
##

**Comment by SergioCrisostomo** [comment]
I'm fine with "switching" or at least "adding" https://gitter.im/mootools/mootools-core as a official communication channel.

**Comment by DimitarChristoff** [comment]
+1 for slack*


--
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by nyov** [comment]
Unless slack.com has gotten much better in regards to open collaboration (non-team member joining chats), I feel IRC is still superior as an open medium. Lot's of clients, easy to join in, while slack and gitter are pretty much browser-only or require some smartphone 'app' to partake.

Slack may be good for companies/teams that have a need to lock down their communications, but it doesn't mesh so well with free software dev communication requirements IMHO.
