### ISSUE TITLE
domready event does not fire on IOS safari

### ISSUE THREAD

**Issue by Adidi** [mootools/mootools-core#2776]
Checked it on iphone 6 in safari - if i set `window.addEvent('domready',callback);` the `callback` won't fire.

**Comment by DimitarChristoff** [comment]
This related to: http://stackoverflow.com/questions/40186332/mootools-click-event-not-working-in-iphone-6 ?

https://jsfiddle.net/1oymyddf/

I am on iphone7 and using mootools 1.6, it fires correctly. 

```html
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/mootools/1.6.0/mootools-core.js"></script>
</head>
<body>
  <script>
window.addEvent('domready', () => {
	alert('Done')
});
  </script>
</body>
</html>
```

so, which version of MooTools do you use?

**Comment by Adidi** [comment]
iphone7 works fine for me. when I used with IOS6 i had this bug - had to switch to native `DOMContentLoaded` for it to work again
