### ISSUE TITLE
Extends: [MyClass] throws "klass is not a constructor"

### ISSUE THREAD

**Issue by CNSKnight** [mootools/mootools-core#2791]
#odd-but-annoying quirk

MooTools.version "1.6.0"

Passing a single-element array to Class.Extends throws "klass is not a constructor"

Replacing `Extends: [MyClass]` with `Extends: MyClass` is handled

**Comment by SergioCrisostomo** [comment]
@CNSKnight can you make a jsFiddle that reproduces this problem?

**Comment by Oliv** [comment]
I think this reproduces the behaviour : [https://jsfiddle.net/68jghwo6/1](https://jsfiddle.net/68jghwo6/1)

**Comment by DimitarChristoff** [comment]
You can only have one super to extend, array does not make any sense. This is not like Implements
