### ISSUE TITLE
Exception error after activating Rev Slider 4.6

### ISSUE THREAD

**Issue by merc28** [mootools/mootools-core#2794]
I got a WordPress error (_see below_) after installing & activating Revolution Slider (4.6) in Gantry 5 framework.
A thread in Rocket Theme forums indicated that the enabling of mootools atom fixed a problem, but i'm not sure.

One other complication i'm facing is that my client may not have access to their Cpanel/file ftp. So I gotta install any atoms via the Gantry 5 / Rocket Theme back end interface.

Any suggestions are appreciated.

`Whoops\Exception\ErrorException thrown with message "Call to a member function get_url() on null"

Stacktrace:
#0 Whoops\Exception\ErrorException in /home7/laughix9/public_html/wp-content/plugins/revslider/includes/template.class.php:136
`

**Comment by swhiteman** [comment]
Can you please provide a URL showing the *JavaScript* side of this problem?  A PHP error isn't going to be relevant.

**Comment by DimitarChristoff** [comment]
The purpose of the issue tracker is to report (possible) bugs with the mootools framework itself. When you are looking for help, you should post this either on the [mailing list](https://groups.google.com/forum/#!forum/mootools-users) or on [StackOverflow](https://stackoverflow.com/questions/tagged/mootools)

Good luck, closing this.

**Comment by merc28** [comment]
Miraculously, i hit the 'back' button and then clicked 'activate' and, poof, rev slider was installed. 

This is a mystery to me. Can someone relate or explain?

Thanks to all who took the time to read this thread.
