### ISSUE TITLE
Change this repo title to HTTPS

### ISSUE THREAD

**Issue by NullPiotrException** [mootools/mootools-core#2800]
It would look better if you changed:
`MooTools Core Repository http://mootools.net`
...to:
`MooTools Core Repository https://mootools.net`

**Comment by DimitarChristoff** [comment]
How bored are you

**Comment by NullPiotrException** [comment]
Just searching the web, asking projects/websites to switch to HTTPS in all places, providing PRs with all URLs changed to HTTPS version if possible, asking also to provide checksums and some other good practices like enabling long passwords.

**Comment by DimitarChristoff** [comment]
this is just something @kamicane or @timwienk can do from the repo settings, SSL is enabled on the box. @timwienk may be able to add a rewrite for any http traffic to https - https://github.com/mootools/website

**Comment by NullPiotrException** [comment]
I planned to make a PR myself for mootools/website. It's just that I work FIFO style and there are some projects I want to do first.
In my latest comment I just explained why I maked such a silly issue.

**Comment by ibolmo** [comment]
Done :)

**Comment by timwienk** [comment]
> @timwienk may be able to add a rewrite for any http traffic to https - https://github.com/mootools/website

That should already be the case. I recall adding a Let's Encypt SSL certificate + certbot stuff some time last year, I assume I added an http-to-https redirect as well in the nginx configuration.

**Comment by DimitarChristoff** [comment]
when you go to forge, SSL cert is compromised because https://github.com/mootools/website/blob/8309396fbaac2496edd9bc31eeaaa7a828a05030/views/layouts/main.jade#L19-L20 /cc @timwienk
