### ISSUE TITLE
Conflict with ecmascript Map

### ISSUE THREAD

**Issue by zortext** [mootools/mootools-core#2802]
I think mootools some how conflicting with ecmascript maps.   Probably it is about Array.from() method.

Run this code with a mootools loaded page.

` console.log(Array.from(new Map(); ))`

This returns a Map instead of Array. 

https://jsfiddle.net/5sgcb3ok/2/

**Comment by DimitarChristoff** [comment]
You are using an outdated version of mootools.

https://github.com/mootools/mootools-core/blob/master/Source/Core/Core.js#L125-L128

`Array.from` got renamed to `Array.convert`. Same jsfiddle with 1.6.0 is fine.

**Comment by zortext** [comment]
Hi thank you for your response. I have the latest version. Problem is
because of the compat layer.

Serkan T.


Dimitar Christoff <notifications@github.com>, 10 Tem 2018 Sal, 15:21
tarihinde şunu yazdı:
