### ISSUE TITLE
Mootools.net down

### ISSUE THREAD

**Issue by PhMetzger** [mootools/mootools-core#2810]
Hello, 

All website of the mootools.net domain are down, is it normal ?

If it should stay offline, is there a way to get an offline version of the documentation here ?

**Comment by timwienk** [comment]
It appears that the `mootools.net` domain was put into `clientHold` status. I'll try to get in contact with the right person to see what's going on.

**Comment by PhMetzger** [comment]
Thank you Tim

Should have look at that, just tell if any help needed

**Comment by timwienk** [comment]
Meanwhile, the docs can be found as markdown files in the repository. Links and references might not be correct, and some things will display differently, but for the most part it should be useable:

https://github.com/mootools/mootools-core/tree/master/Docs

**Comment by timwienk** [comment]
I haven't been able to reach Valerio.

I've temporarily set up the website on a subdomain of mine:
- https://mootools.wienk.net/
- https://demos111.mootools.wienk.net/
- https://docs111.mootools.wienk.net/

Will redirect that domain back to mootools.net if/when we get control over it.

**Comment by timwienk** [comment]
We're back! :tada:

**Comment by Imobach** [comment]
Looks like the mootools site is still down.

**Comment by timwienk** [comment]
It's "again" (not "still"), same issue as last year. @kamicane ?

> I've temporarily set up the website on a subdomain of mine:
> 
> * https://mootools.wienk.net/
> * https://demos111.mootools.wienk.net/
> * https://docs111.mootools.wienk.net/

These temporary things are up again.

**Comment by kamicane** [comment]
<Insert insightful emoji here> I did an oopsie. Fixed. Should be back up now.
