### ISSUE TITLE
mootools.net down

### ISSUE THREAD

**Issue by PhMetzger** [mootools/mootools-core#2835]
Hello,

All website of the mootools.net domain are down, is it normal ?

If it should stay offline, is there a way to get an offline version of the documentation here, or is it any way to help ?

**Comment by rlorenzo** [comment]
I also looked for the documentation and found the website down. Tracking this to see when it will be resolved.

**Comment by timwienk** [comment]
The website is up again. The old hosting setup has stopped, as part of Mediatemple's merge with Godaddy. We've set up the most important parts on another setup.

Note that the Docs are always available [on Github](https://github.com/mootools/mootools-core/tree/master/Docs), as their source Markdown files.
